### PR TITLE
49 allow a nicer access to the names of the bodies for a loaded model

### PR DESCRIPTION
**Pull request by JamieMair**
Added a prototype of how to perform named accessing (see https://github.com/JamieMair/MuJoCo.jl/issues/49). 

API needs a little bit of work, and benchmarking still needs to check whether we need something faster. As of now this should be O(1) just like python, but we have the option of compiling the names into the type of the model if there are any issues.

## Example:
```julia
using MuJoCo
using MuJoCo.NamedAccess
model, data = MuJoCo.sample_model_and_data()
named_model = NamedModel(model)

torso = body(named_model, :torso) # should be a thin wrapper, with no copying
# can tab-complete on torso to find types
torso.pos  # returns a view into the array

# can also access via the index
torso_by_idx = body(named_model, 2)

using Test
@test torso == torso_by_idx
```

## Functions exported by `MuJoCo.NamedAccess`:
**Note: Aliases are shown with a ()**
- light
- cam (camera)
- actuator
- body
- geom
- jnt (joint)
- sensor
- site
- tendon (ten)
- eq (equality)
- key (keyframe)
- numeric
- mat (material)
- tex (texture)
- pair
- hfield
- tuple
- skin
- exclude

Remaining tasks:
- [x] Add a pretty printer for the structs
- [ ] ~~Actually test whether we are accessing the right things~~ Deferred to https://github.com/JamieMair/MuJoCo.jl/issues/60

### CODE REVIEW

**Review by nic-barbara — COMMENTED** [review]
This is looking really good so far, but yep I think we need a pretty print before we merge it because it's difficult to know what options are actually available to the user at the moment.

**Comment by nic-barbara** [comment]
Can we also introduce an `id` field to (for example) the named bodies? In the Python bindings, the user can specify `model.body('torso').id` which is useful since this information is required by functions like `mj_jacBodyCom`. At the moment, I think that ID can only be accessed in Julia either by
```julia
id_torso = LibMuJoCo.mj_name2id(model, LibMuJoCo.mjOBJ_XBODY, "torso")
```
or with
```julia
named_model = NamedModel(model)
torso = body(named_model, :torso)
torso.weldid
```
which is a little un-intuitive, particularly if it's needed reasonably often. Maybe just simply using `id` instead of `weldid`, or documenting clearly that these are equivalent, would be enough?

**Comment by nic-barbara** [comment]
It would also be good to associate a `name` field with each of the named objects extracted. For example, if I have
```julia
my_joint = joint(named_model, 1)
```
then it would be nice to be able to look at `my_joint.name`, the corresponding name of the joint with ID `1`.

See [here](https://github.com/JamieMair/MuJoCo.jl/blob/example/humanoid-lqr/examples/humanoid_lqr.jl#L125) for an example of where this might be useful:

**Comment by nic-barbara** [comment]
Another quick note - I think it's a bit tedious to get the user to have to write out
```julia
using MuJoCo
using MuJoCo.LibMuJoCo
using MuJoCo.Wrappers
using MuJoCo.NamedAccess
```
if they want to use all the features of the named wrappers. I think anyone who would want to use base MuJoCo functions within `LibMuJoCo` would also want to use the wrappers and possibly the named access.

In particular, it'd be nice to re-export the `Model` and `Data` types with the main `MuJoCo` module so that users don't have to import `LibMuJoCo` if they want to write their own functions which depend on the model and data types (eg: a `reset!(m::Model, d::Data)` or something similar).

**Comment by JamieMair** [comment]
@nic-barbara Agreed to all comments. I have made some changes so that we don't actually *need* the NamedModel (or rather, users don't need it). I have kept it in for now as it is useful for testing the other API using the basic model and data. At some point I want to benchmark the difference between the two, and perhaps we can turn NamedModel into a more efficient way of accessing the views (as we can put the lookup in the type info and then compile all those checks away during JIT). 

I have also added some amount of pretty printing, e.g.
```julia
julia> body(model, "torso")
ModelBody:
id:           1
name:         "torso"
parentid:     (1 x  )   Int32   [0]
rootid:       (1 x  )   Int32   [1]
weldid:       (1 x  )   Int32   [1]
mocapid:      (1 x  )   Int32   [-1]
jntnum:       (1 x  )   Int32   [1]
jntadr:       (1 x  )   Int32   [0]
dofnum:       (1 x  )   Int32   [6]
dofadr:       (1 x  )   Int32   [0]
geomnum:      (1 x  )   Int32   [2]
geomadr:      (1 x  )   Int32   [1]
simple:       (1 x  )   UInt8   [0]
sameframe:    (1 x  )   UInt8   [0]
pos:          (3 x  )   Float64 [0.0, 0.0, 1.282] (4 s.f.)
quat:         (4 x  )   Float64 [1.0, 0.0, 0.0, 0.0] (4 s.f.)
ipos:         (3 x  )   Float64 [-0.003864, 0.0, -0.04637] (4 s.f.)
iquat:        (4 x  )   Float64 [0.9991, 0.0, 0.04156, 0.0] (4 s.f.)
mass:         (1 x  )   Float64 [5.854] (4 s.f.)
subtreemass:  (1 x  )   Float64 [40.84] (4 s.f.)
inertia:      (3 x  )   Float64 [0.05127, 0.03197, 0.03115] (4 s.f.)
invweight0:   (2 x  )   Float64 [0.0527, 3.23] (4 s.f.)
user:         (0 x  )   Float64 [] (4 s.f.)
```

Which should work for all the types exported. This is along with tab completion on the objects in the repl.

Also added raw documentation of the functions, e.g.:
```julia
help?> body
search: body mj_jacBody mj_jacBodyCom BoundsError broadcast broadcast! Broadcast @boundscheck @inbounds clipboard checkbounds isblockdev baremodule LineNumberNode

  body([model, data], [name, index])

  Creates an object with access to views of the supplied model or data object, based either on an index or a name. Properties available are: (id, name, applied, xpos, xquat, xmat, xipos,  ximat, com, cinert, crb, cvel, linvel, angmom, cacc, int, ext)
  ```
  
  Finally, I have added some exports to re-export things from LibMuJoCo. Now when someone uses MuJoCo, they should have access to all the functions. I do not rexport the NamedAccess functions as these are pretty common names and may pollute the namespace of users. In the docs we can add a suggestion like "use `import MuJoCo.NamedAccess as na`" and then called `na.body(model, "torso")`.

**Comment by nic-barbara** [comment]
@JamieMair These changes look great. With the pretty printing, do you think we could extend this to `NamedModel` and `NamedData` too? It would be nice to see all the "components" of the model (eg: `:shin_right`, `:pelvis`, `:thigh_left`, etc) to know what bodies/joints/actuators etc. are available without having to look through the .xml file.

**Comment by nic-barbara** [comment]
I think we'll also need to either add `+1` to all IDs and indices, or very clearly document that the body/joint/other indexing starts at 0. This is an easy place to introduce a bug.

**Comment by nic-barbara** [comment]
I've opened https://github.com/JamieMair/MuJoCo.jl/pull/57 which uses many of the features being developed for this PR with named access. The humanoid LQR example in https://github.com/JamieMair/MuJoCo.jl/pull/57 is currently a fully functional replica of the [Deep Mind tutorial](https://colab.research.google.com/github/deepmind/mujoco/blob/main/python/LQR.ipynb), but some of the syntax is still a little clunky. I think it's a good reference point for usability of the named model/data features being developed here.

**Comment by JamieMair** [comment]
> @JamieMair These changes look great. With the pretty printing, do you think we could extend this to `NamedModel` and `NamedData` too? It would be nice to see all the "components" of the model (eg: `:shin_right`, `:pelvis`, `:thigh_left`, etc) to know what bodies/joints/actuators etc. are available without having to look through the .xml file.
> 
> Also, can the functions like `body` and `joint` be extended to also take a string instead of just a symbol as the name? I think that would improve usability too.

I have opened https://github.com/JamieMair/MuJoCo.jl/issues/58 for this.

**Comment by JamieMair** [comment]
> I think we'll also need to either add `+1` to all IDs and indices, or very clearly document that the body/joint/other indexing starts at 0. This is an easy place to introduce a bug.

I think this would be better for documentation. I would prefer to use the underlying C ids as much as possible, and avoid thinking of them as indexes. But it is important for it to be documented. We should add this to - https://github.com/JamieMair/MuJoCo.jl/issues/22

**Pull request merged**
